name: Sync upstream
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync upstream to branch
        uses: repo-sync/repo-sync@v2
        with:
          source_repo: warperia/warperia-frontend
          source_branch: main
          destination_branch: upstream
          github_token: ${{ secrets.GITHUB_TOKEN }}
